production:
  whl_daily_data_update:
    class: WhlDailyUpdateJob
    queue: default
    schedule: at 9:00am every day

  whl_daily_model_refresh:
    class: WhlDailyModelRefreshJob
    queue: default
    schedule: at 9:30am every day
